function info = get_info()
    width = 9;
    height = 9;
    times = -540:+540;
    num_times = length(times);
    num_delays = 150;
    probe_time_resolution = 7;
    num_folds = 1;
    
    % todo:
    % - `h17_STA_non_linearity_42th_try` to `sta`
    % - what is the meaning of `sta`
    assets_folder = 'assets';
    folders = struct(...
        'assets',assets_folder,...
        'data',fullfile(assets_folder,'data'),...
        'sta',fullfile(assets_folder,'sta'),...
        'bases',fullfile(assets_folder,'bases'),...
        'profiles',fullfile(assets_folder,'profiles'),...
        'BS',fullfile(assets_folder,'BS'),...
        'models',fullfile(assets_folder,'models'),...
        'results',fullfile(assets_folder,'results'));
    
    info = struct(...
        'width',width,...
        'height',height,...
        'times',times,...
        'num_times',num_times,...
        'num_delays',num_delays,...
        'probe_time_resolution',probe_time_resolution,...
        'num_folds',num_folds,...
        'folders',folders);
end